#!/bin/bash

focused=$(swaymsg -t get_tree | jq -r '.. | select(.nodes?) | .floating_nodes[] | recurse(.nodes[]) as $parent | select($parent.focused==true).id')

if [[ -z "$focused" ]];then
    focused=$(swaymsg -t get_tree | jq -r '.. | select(.layout?=="tabbed") | select(.type=="con") | recurse(.nodes[]) as $parent | select($parent.focused==true).id' | head -n1)
fi

swaymsg [con_id="$focused"] focus

echo $focused
