#!/bin/bash

workspc=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused==true).name')
con_ids=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused==true).floating_nodes[].id')
con_ids_hidden=$(swaymsg -t get_workspaces | jq -r '.[] | select(.name=='\"floating$workspc\"').floating_nodes[].id')

# Use con_id to iterate through containers from $con_ids instead of windows
if [[ $1 = "hide" ]];then
    for con_id in $con_ids;do
	swaymsg [con_id="$con_id"] move container to workspace "floating$workspc", mark "$workspc"
    done
    swaymsg workspace "$workspc"
elif [[ $1 = "show" ]];then
    for con_id_h in $con_ids_hidden;do
	swaymsg [con_id="$con_id_h"] move container to workspace "$workspc"
    done
    swaymsg focus floating
fi

swaymsg mode "default"
