#!/bin/bash

if [ $1 = "on" ];then
    curl   -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2ZjVjZTY1ZWNkNGU0YjMwYWNkMWNlOTUwNjIyZTdiNCIsImlhdCI6MTcwMzU2MDE2NiwiZXhwIjoyMDE4OTIwMTY2fQ.b1GPbLrlNOFvxTNiGuPWi6ktGVS8g38Dol8jRUE5uIw"   -H "Content-Type: application/json"   -d '{"entity_id": "light.smart_bulb"}'  http://localhost:8123/api/services/light/turn_on
    exit
fi

if [ $1 = "off" ];then
    curl   -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2ZjVjZTY1ZWNkNGU0YjMwYWNkMWNlOTUwNjIyZTdiNCIsImlhdCI6MTcwMzU2MDE2NiwiZXhwIjoyMDE4OTIwMTY2fQ.b1GPbLrlNOFvxTNiGuPWi6ktGVS8g38Dol8jRUE5uIw"   -H "Content-Type: application/json"   -d '{"entity_id": "light.smart_bulb"}'  http://localhost:8123/api/services/light/turn_off
    exit
fi

if [ $1 = "temp" ];then
    curl   -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2ZjVjZTY1ZWNkNGU0YjMwYWNkMWNlOTUwNjIyZTdiNCIsImlhdCI6MTcwMzU2MDE2NiwiZXhwIjoyMDE4OTIwMTY2fQ.b1GPbLrlNOFvxTNiGuPWi6ktGVS8g38Dol8jRUE5uIw"   -H "Content-Type: application/json"   -d "{\"entity_id\": \"light.smart_bulb\", \"color_temp\": \"$2\"}"  http://localhost:8123/api/services/light/turn_on
    exit
fi

if [ $1 = "brightness" ];then
    curl   -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2ZjVjZTY1ZWNkNGU0YjMwYWNkMWNlOTUwNjIyZTdiNCIsImlhdCI6MTcwMzU2MDE2NiwiZXhwIjoyMDE4OTIwMTY2fQ.b1GPbLrlNOFvxTNiGuPWi6ktGVS8g38Dol8jRUE5uIw"   -H "Content-Type: application/json"   -d "{\"entity_id\": \"light.smart_bulb\", \"brightness\": \"$2\"}"  http://localhost:8123/api/services/light/turn_on
    exit
fi

if [ $1 = "toggle" ];then
    curl   -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2ZjVjZTY1ZWNkNGU0YjMwYWNkMWNlOTUwNjIyZTdiNCIsImlhdCI6MTcwMzU2MDE2NiwiZXhwIjoyMDE4OTIwMTY2fQ.b1GPbLrlNOFvxTNiGuPWi6ktGVS8g38Dol8jRUE5uIw"   -H "Content-Type: application/json"   -d "{\"entity_id\": \"light.smart_bulb\"}"  http://localhost:8123/api/services/light/toggle
    exit
fi


if [ $1 = "color" ];then
    if [ -z "$2" ];then
	echo -n "aliceblue,
antiquewhite,
aqua,
aquamarine,
azure,
beige,
bisque,
blanchedalmond,
blue,
blueviolet,
brown,
burlywood,
cadetblue,
chartreuse,
chocolate,
coral,
cornflowerblue,
cornsilk,
crimson,
cyan,
darkblue,
darkcyan,
darkgoldenrod,
darkgray,
darkgreen,
darkgrey,
darkkhaki,
darkmagenta,
darkolivegreen,
darkorange,
darkorchid,
darkred,
darksalmon,
darkseagreen,
darkslateblue,
darkslategray,
darkslategrey,
darkturquoise,
darkviolet,
deeppink,
deepskyblue,
dimgray,
dimgrey,
dodgerblue,
firebrick,
floralwhite,
forestgreen,
fuchsia,
gainsboro,
ghostwhite,
gold,
goldenrod,
gray,
green,
greenyellow,
grey,
honeydew,
hotpink,
indianred,
indigo,
ivory,
khaki,
lavender,
lavenderblush,
lawngreen,
lemonchiffon,
lightblue,
lightcoral,
lightcyan,
lightgoldenrodyellow,
lightgray,
lightgreen,
lightgrey,
lightpink,
lightsalmon,
lightseagreen,
lightskyblue,
lightslategray,
lightslategrey,
lightsteelblue,
lightyellow,
lime,
limegreen,
linen,
magenta,
maroon,
mediumaquamarine,
mediumblue,
mediumorchid,
mediumpurple,
mediumseagreen,
mediumslateblue,
mediumspringgreen,
mediumturquoise,
mediumvioletred,
midnightblue,
mintcream,
mistyrose,
moccasin,
navajowhite,
navy,
navyblue,
oldlace,
olive,
olivedrab,
orange,
orangered,
orchid,
palegoldenrod,
palegreen,
paleturquoise,
palevioletred,
papayawhip,
peachpuff,
peru,
pink,
plum,
powderblue,
purple,
red,
rosybrown,
royalblue,
saddlebrown,
salmon,
sandybrown,
seagreen,
seashell,
sienna,
silver,
skyblue,
slateblue,
slategray,
slategrey,
snow,
springgreen,
steelblue,
tan,
teal,
thistle,
tomato,
turquoise,
violet,
wheat,
white,
whitesmoke,
yellow,
yellowgreen"
	exit
    fi    
	
    curl   -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2ZjVjZTY1ZWNkNGU0YjMwYWNkMWNlOTUwNjIyZTdiNCIsImlhdCI6MTcwMzU2MDE2NiwiZXhwIjoyMDE4OTIwMTY2fQ.b1GPbLrlNOFvxTNiGuPWi6ktGVS8g38Dol8jRUE5uIw"   -H "Content-Type: application/json"   -d "{\"entity_id\": \"light.smart_bulb\", \"color_name\": \"$2\", \"brightness\": \"255\"}"  http://localhost:8123/api/services/light/turn_on
    exit
fi



exit
