#!/bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &


#bspc monitor HDMI-A-0 -d 1 2 3 4 5
bspc monitor -d 1 2 3 4 5
bspc desktop -f 1

# config
bspc config border_width         0
bspc config window_gap           0
bspc config focused_border_color "#DC143C"
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true
#bspc config presel_feedback_color "#6F0000"

# rules
#bspc rule -a '*' state=floating
bspc rule -a Alacritty:Alacritty:ranger center=on state=floating rectangle=1528x597+0+0
bspc rule -a Alacritty:Alacritty:alacritty state=floating center=on
bspc rule -a feh state=fullscreen
bspc rule -a Pavucontrol state=floating
bspc rule -a emacs:Emacs state=tiled

# startup message
#sleep 1.9
#xwinwrap -b -s -fs -st -sp -nf -ov -fdt -- mpv -wid WID --framedrop=vo --no-osc --no-input-builtin-bindings /home/g/images/startup.mp4

#nice xwinwrap -b -s -fs -st -sp -nf -ov -fdt -- mpv -wid WID --really-quiet --framedrop=vo --no-audio --no-osc --no-input-builtin-bindings --loop --panscan="1.0" "${HOME}/images/gifs/cover.mp4" &

# load colors (imagemagick necessary)
wal -c
wal -n -i ~/images/cover.png
. ~/.cache/wal/colors.sh

# set wallpaper
#feh --no-fehbg --bg-fill ~/images/cover.png
bspc config presel_feedback_color $color3

# polybar
#python ~/dotfiles/wal/wal-polybar.py
#polybar &

# compositor and sxhkd
#picom -b
sxhkd &

# launch third-party programs
# docker restart homeassistant &

# misc
#setxkbmap -layout us,ru -option "grp:alt_shift_toggle"
#xsetroot -cursor_name left_ptr
#unclutter -jitter 15 -idle 5 -root &
