#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         0
bspc config window_gap           0
bspc config focused_border_color "#DC143C"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true
bspc config presel_feedback_color "#6F0000"
bspc rule -a st-256color:st-256color:ranger center=on state=floating rectangle=1200x500+0+0
bspc rule -a st-256color:st-256color:stfloat state=floating center=on
bspc rule -a st-256color:st-256color:htop desktop=^1
bspc rule -a feh state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Nvidia-settings state=floating


f=png
if [[ -e "${HOME}/images/cover.jpg" ]];then
	f=jpg
fi

m=gif
if [[ -e "${HOME}/images/gifs/cover.mp4" ]];then
        m=mp4
fi

feh --no-fehbg --bg-fill ~/images/cover.$f

picom -b --blur-background --backend glx
#nice xwinwrap -b -s -fs -st -sp -nf -ov -fdt -- mpv -wid WID --really-quiet --framedrop=vo --no-audio --no-osc --no-input-builtin-bindings --loop --panscan="1.0" "${HOME}/images/gifs/cover.$m" &

setxkbmap -layout us,ru -option grp:shifts_toggle -option grp_led:caps
xsetroot -cursor_name left_ptr
unclutter -jitter 15 -idle 5 -root &

#st -t htop -e htop &
