#!/bin/bash

for win in $(bspc query -N -n .hidden.local.window)
do
	window+="$win - $(xprop -id $win | grep ^WM_NAME | awk '{for(i=3;i<=NF;++i) printf "%s ",$i;print ""}' | sed 's/"//g')\n"
done


list_hidden () {
    for n in $(bspc query -N -n .hidden.local.window);do
	printf "$n - $(xprop -id "$n" WM_NAME | sed 's/.*=//' | sed 's/\"//g' 2>/dev/null)\n"
    done
}

selected=$(list_hidden | ~/dotfiles/bspwm/dmenu -p hidden)

[[ -z $selected ]] && exit;

bspc node $(echo $selected | awk '{print $1}') --flag hidden=off

bspc node -f $(echo $selected | awk '{print $1}')

