#!/bin/bash

marked=$(bspc query -N -n .local.marked)

get_wm_class () {
    echo $(xprop -id "$1" WM_CLASS | sed 's/.*=//' | sed 's/\"//g' | awk '{print $NF}' 2>/dev/null)
}

if [[ $2 = "tabbed" ]];then
    focused=$(bspc query -N -n)
    tabbed="$focused"

    if [[ $(get_wm_class "$focused") != "tabbed" ]];then
	tabbed=$(tabbed -d)
	xdotool windowreparent "$focused" "$tabbed"
    fi

    if [[ -z $marked ]];then
        exit
    fi

    for m in $marked;do
        xdotool windowreparent "$m" "$tabbed"
        bspc node "$m" -g marked
    done

    exit
fi
