#!/bin/bash

windows=$(bspc query -N -n .window.!hidden)
desktops=$(bspc query -D --names)
focused_desktop=$(bspc query -D -d)

get_wm_name () {
    echo $(xprop -id "$1" WM_NAME | sed 's/.*=//' | sed 's/\"//g' 2>/dev/null)
}

get_wm_class () {
    echo $(xprop -id "$1" WM_CLASS | awk '{print $NF}' | sed 's/\"//g' 2>/dev/null)
}

wm_flags () {
    if [[ $1 = "marked" ]];then
        nodes=$(bspc query -N -n .marked)
    fi
    
    if [[ $1 = "sticky" ]];then
        nodes=$(bspc query -N -n .sticky)
    fi

    if [[ $1 = "locked" ]];then
        nodes=$(bspc query -N -n .locked)
    fi

    if [[ $1 = "hidden" ]];then
        nodes=$(bspc query -N -n .hidden)
    fi
    
    [[ -z $nodes ]] && return 1
    
    for n in $nodes;do
	info=$(get_wm_name "$n")
	printf "$(bspc query -D -n $n --names): $info\n"
    done

    return 0
}

if [[ $1 = "flags" ]];then
    wm_flags "$2"
    exit
fi

if [[ $1 = "class" ]];then
        windows=$(bspc query -N -n .local.window)
        
        for window in $windows;do
            wm_class=$(xprop -id "$window" WM_CLASS | awk '{ print $3 }' | sed 's/[\",]//g')
            
            if [[ -z $2 ]];then
                printf "%s\n" "$wm_class"
            else
                if [[ $2 = $wm_class ]];then
                    echo "$window"
                    exit 1
                fi
            fi
        done

        exit 0
fi

for d in $desktops;do
    nodes=$(bspc query -d "$d" -N -n .window.!hidden)
    [[ -z $nodes ]] && continue
    
    printf "$d:\n"
    for n in $nodes;do
	info=$(get_wm_name "$n")
	class=$(get_wm_class "$n")
	
	if [[ $class = "tabbed" ]];then
	    printf "tabbed: "
	fi
	
	printf "$info\n"
    done
    printf "\n"
done

