#!/bin/bash

if [[ $1 = "all" ]];then
    for p in {windows,flags};do
        ~/dotfiles/bspwm/notification_info $p
    done
    exit
fi

if [[ $1 = "date" ]];then
    #dunstify -h "string:bgcolor:#000000" -h "string:x-dunst-stack-tag:date" \
    #"$(date "+%d/%m %a/%h %H:%M:%S") mem: $(free -m | grep Mem: | awk '{print $3}')" \
    #"$(printf "$(cal)")" \

    printf "$(date "+%d/%m %a/%h %H:%M:%S") mem: $(free -m | awk 'NR==2{print $3}')\n$(cal)\n$(~/dotfiles/bspwm/notification_info volume)" | ~/dotfiles/bspwm/dmenu -l 20 
    exit
fi

if [[ $1 = "windows" ]];then
    #dunstify \
    #    -h "string:bgcolor:#000000" \
    #    -h "string:x-dunst-stack-tag:windows" \
    #    "$(printf "windows:\n$(~/dotfiles/bspwm/nodes info | sort)\
    #    \nhidden:\n$(~/dotfiles/bspwm/nodes info hidden | sort)") " 

    printf "$(~/dotfiles/bspwm/nodes)\n$(~/dotfiles/bspwm/notification_info flags)" | ~/dotfiles/bspwm/dmenu -l 20
    exit
fi

if [[ $1 = "volume" ]];then
    volume=$(amixer get Master | tail -1 | awk '{print $5}' | sed 's/[^0-9]//g')
    mute=$(amixer get Master | tail -1 | awk '{print $6}')
    sink_name=$(pactl get-default-sink | sed 's/\./ /g' | awk '{print $NF}')

    if [[ $mute = "[on]" ]];then
        mute=
    fi
    #dunstify -t 1000 -h string:bgcolor:#000000 -h string:hlcolor:#6F0000 -h string:frcolor:#000000 -h string:x-dunst-stack-tag:volume -h int:value:"$volume" "$(printf "$sink_name\n$volume $mute")"
    printf "$sink_name\n$volume $mute"
    exit
fi

if [[ $1 = "flags" ]];then
    hidden=$(~/dotfiles/bspwm/nodes flags hidden)
    if [[ -n $hidden ]];then
	printf "\nhidden:\n$hidden\n"
    fi
    marked=$(~/dotfiles/bspwm/nodes flags marked)
    if [[ -n $marked ]];then
	printf "\nmarked:\n$marked\n"
    fi
    sticky=$(~/dotfiles/bspwm/nodes flags sticky)
    if [[ -n $sticky ]];then
	printf "\nsticky:\n$sticky\n"
    fi
    locked=$(~/dotfiles/bspwm/nodes flags locked)
    if [[ -n $locked ]];then
	printf "\nlocked:\n$locked\n"
    fi
    

    #dunstify -h string:bgcolor:#000000 -h string:x-dunst-stack-tag:flags "$(printf "marked:\n$marked\nsticky:\n$sticky\nlocked:\n$locked")"
    exit
fi
