#!/bin/bash

if [[ -z "$1" ]];then
    exit
fi

if [[ $1 = "reset" ]];then
    swaymsg input type:keyboard xkb_layout "us"
    exit
fi

layout=$(echo "$1" | sed 's/ /\n/g')

kmap=$(printf "$layout" | ~/dotfiles/bspwm/dmenu -p kmap)

if [[ -z $kmap ]];then
    exit
fi

#setxkbmap $kmap
echo a
swaymsg input type:keyboard xkb_layout "$kmap"
