#!/bin/bash

if [[ -f /tmp/.temp ]];then
    s=$(cat /tmp/.temp)
else   
    s=0
fi

if [[ -n $1 ]];then
    if [[ $1 = "clear" ]];then
        echo > /tmp/.temp
        exit
    fi

    if [[ $1 = "save" ]];then
        s=$(($s + 1))
        m=$(($s / 60))
        h=$(($m / 60))
        echo "$h"h:"$(($m % 60))"m:"$(($s % 60))"s >> ~/.temp_list
        exit
    fi

    if [[ $1 = "set" ]];then
        s=$2
    fi
fi

while true;do
        s=$(($s + 1))
        m=$(($s / 60))
        h=$(($m / 60))
        echo "$h"h:"$(($m % 60))"m:"$(($s % 60))"s
        echo $s > /tmp/.temp
        sleep 1
        clear
done
