#!/bin/bash

f=$(bspc query -N -n .window.local.floating)

if [[ -n $(bspc query -N -n focused.floating) ]];then
    for w in $f;do
        bspc node "$w" -l normal
    done
else
    for w in $f;do
        bspc node "$w" -l below
    done
fi
