;;; xelb-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from xcb.el

(register-definition-prefixes "xcb" '("xcb:"))


;;; Generated autoloads from xcb-bigreq.el

(register-definition-prefixes "xcb-bigreq" '("xcb:bigreq:"))


;;; Generated autoloads from xcb-composite.el

(register-definition-prefixes "xcb-composite" '("xcb:composite:"))


;;; Generated autoloads from xcb-cursor.el

(register-definition-prefixes "xcb-cursor" '("xcb:cursor:-"))


;;; Generated autoloads from xcb-damage.el

(register-definition-prefixes "xcb-damage" '("xcb:damage:"))


;;; Generated autoloads from xcb-dbe.el

(register-definition-prefixes "xcb-dbe" '("xcb:dbe:"))


;;; Generated autoloads from xcb-debug.el

(register-definition-prefixes "xcb-debug" '("xcb-debug:"))


;;; Generated autoloads from xcb-dpms.el

(register-definition-prefixes "xcb-dpms" '("xcb:dpms:"))


;;; Generated autoloads from xcb-dri2.el

(register-definition-prefixes "xcb-dri2" '("xcb:dri2:"))


;;; Generated autoloads from xcb-dri3.el

(register-definition-prefixes "xcb-dri3" '("xcb:dri3:"))


;;; Generated autoloads from xcb-ewmh.el

(register-definition-prefixes "xcb-ewmh" '("xcb:ewmh:"))


;;; Generated autoloads from xcb-ge.el

(register-definition-prefixes "xcb-ge" '("xcb:ge:"))


;;; Generated autoloads from xcb-glx.el

(register-definition-prefixes "xcb-glx" '("xcb:glx:"))


;;; Generated autoloads from xcb-icccm.el

(register-definition-prefixes "xcb-icccm" '("xcb:icccm:"))


;;; Generated autoloads from xcb-keysyms.el

(register-definition-prefixes "xcb-keysyms" '("xcb:keysyms:"))


;;; Generated autoloads from xcb-present.el

(register-definition-prefixes "xcb-present" '("xcb:present:"))


;;; Generated autoloads from xcb-randr.el

(register-definition-prefixes "xcb-randr" '("xcb:randr:"))


;;; Generated autoloads from xcb-record.el

(register-definition-prefixes "xcb-record" '("xcb:record:"))


;;; Generated autoloads from xcb-render.el

(register-definition-prefixes "xcb-render" '("xcb:render:"))


;;; Generated autoloads from xcb-renderutil.el

(register-definition-prefixes "xcb-renderutil" '("xcb:renderutil:"))


;;; Generated autoloads from xcb-res.el

(register-definition-prefixes "xcb-res" '("xcb:res:"))


;;; Generated autoloads from xcb-screensaver.el

(register-definition-prefixes "xcb-screensaver" '("xcb:screensaver:"))


;;; Generated autoloads from xcb-shape.el

(register-definition-prefixes "xcb-shape" '("xcb:shape:"))


;;; Generated autoloads from xcb-shm.el

(register-definition-prefixes "xcb-shm" '("xcb:shm:"))


;;; Generated autoloads from xcb-sync.el

(register-definition-prefixes "xcb-sync" '("xcb:sync:"))


;;; Generated autoloads from xcb-systemtray.el

(register-definition-prefixes "xcb-systemtray" '("xcb:"))


;;; Generated autoloads from xcb-types.el

(register-definition-prefixes "xcb-types" '("xcb:"))


;;; Generated autoloads from xcb-xc_misc.el

(register-definition-prefixes "xcb-xc_misc" '("xcb:xc_misc:"))


;;; Generated autoloads from xcb-xembed.el

(register-definition-prefixes "xcb-xembed" '("xcb:xembed:"))


;;; Generated autoloads from xcb-xevie.el

(register-definition-prefixes "xcb-xevie" '("xcb:xevie:"))


;;; Generated autoloads from xcb-xf86dri.el

(register-definition-prefixes "xcb-xf86dri" '("xcb:xf86dri:"))


;;; Generated autoloads from xcb-xf86vidmode.el

(register-definition-prefixes "xcb-xf86vidmode" '("xcb:xf86vidmode:"))


;;; Generated autoloads from xcb-xfixes.el

(register-definition-prefixes "xcb-xfixes" '("xcb:xfixes:"))


;;; Generated autoloads from xcb-xim.el

(register-definition-prefixes "xcb-xim" '("xim:"))


;;; Generated autoloads from xcb-xinerama.el

(register-definition-prefixes "xcb-xinerama" '("xcb:xinerama:"))


;;; Generated autoloads from xcb-xinput.el

(register-definition-prefixes "xcb-xinput" '("xcb:xinput:"))


;;; Generated autoloads from xcb-xkb.el

(register-definition-prefixes "xcb-xkb" '("xcb:xkb:"))


;;; Generated autoloads from xcb-xlib.el

(register-definition-prefixes "xcb-xlib" '("xlib:X"))


;;; Generated autoloads from xcb-xprint.el

(register-definition-prefixes "xcb-xprint" '("xcb:xprint:"))


;;; Generated autoloads from xcb-xproto.el

(register-definition-prefixes "xcb-xproto" '("xcb:"))


;;; Generated autoloads from xcb-xselinux.el

(register-definition-prefixes "xcb-xselinux" '("xcb:xselinux:"))


;;; Generated autoloads from xcb-xsettings.el

(register-definition-prefixes "xcb-xsettings" '("xcb:xsettings:-"))


;;; Generated autoloads from xcb-xtest.el

(register-definition-prefixes "xcb-xtest" '("xcb:xtest:"))


;;; Generated autoloads from xcb-xv.el

(register-definition-prefixes "xcb-xv" '("xcb:xv:"))


;;; Generated autoloads from xcb-xvmc.el

(register-definition-prefixes "xcb-xvmc" '("xcb:xvmc:"))


;;; Generated autoloads from xelb-test.el

(register-definition-prefixes "xelb-test" '("xelb-test-"))

;;; End of scraped data

(provide 'xelb-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xelb-autoloads.el ends here
