:PROPERTIES:
:ID:       e62fd032-4fd3-4508-bbb8-aaf0029adbaa
:END:
#+title: spacing effect

The spacing effect demonstrates that learning is more effective when study sessions are spaced out.

This effect shows that more information is *encoded into long term memory by spaced study sessions*.

* Causes

Shaughnessy (1977) found that the spacing effect is not robust for items presented twice after a 24-hour delay in testing. However, the spacing effect *is present for items presented four or six times* and tested *after a 24-hour delay*.

The result was interesting because other studies using only twice-presented items have shown a strong spacing effect, although the lag between learning and testing was longer.

Shaughnessy interprets it as evidence that *no single explanatory mechanism* can be used to account for the various manifestations of the spacing effect.

* Semantic priming

(Challis, 1993; Russo & Mammaralla, 2002). Challis found a spacing effect for target words using a frequency estimation task after words were incidentally analyzed *semantically*.

However, no spacing effect was found when the target words were shallowly encoded using a graphemic study task. This suggests that [[id:f20aa917-9844-4473-8116-9f5a88cbccb6][*semantic priming*]] underlies the [[id:e62fd032-4fd3-4508-bbb8-aaf0029adbaa][spacing effect]] in cued-memory tasks.

Upon a recognition memory test, there was no spacing effect found for the *nonwords presented in different fonts* during study. These results support the hypothesis that *short-term perceptual priming* is the mechanism that supports the spacing effects in cued-memory tasks when unfamiliar stimuli are used as targets.

* Applications in education

Studies have shown that long-term spacing effects are prevalent in learning and produce significant learning gains, particularly when the spacing gaps are on the *order of days or weeks*.

Although it is accepted that spacing is beneficial in learning a subject well and previous units should be revisited and practiced, textbooks are written in discrete chapters that do not support these findings.

Rohrer conducted a two-part study in 2006 where students were taught how to solve math problems.

In part 1, students either used mass or spaced practice, and *spaced practice showed significant improvement* over mass practice when tested one week later.

In the second part of the experiment, practice problems were either grouped by type or mixed randomly. The desirable difficulties encountered by the randomly mixed problems were effective, and the performance by *students who solved the randomly mixed problems was vastly superior* to the students who solved the problems grouped by type. 

The reasoning behind this increased performance was that students know the formula for solving equations, but do not always know when to apply the formula. By shuffling problems around and dispersing them across multiple chapters, students also learn to identify when it is appropriate to use which formula. 
