:PROPERTIES:
:ID:       c38ebb89-294c-4d3e-aad8-549cc5fb7c10
:END:
#+title: numerical integration

In [[id:dec88d48-eef6-488e-b6ec-f73ca5367323][numerical analysis]], numerical integration comprises a broad *family of algorithms* for calculating the numerical value of a *definite integral*.

The basic problem in numerical integration is to *compute an approximate solution* to a definite integral to a *given degree of accuracy*.

There are several reasons for carrying out numerical integration:

- The integrand f(x) *may be known only at certain points*, such as obtained by sampling. Some embedded systems and other computer applications may need numerical integration for this reason.

- A formula for the integrand may be known, but it may be *difficult or impossible to find an antiderivative* that is an elementary function. An example of such an integrand is $f(x) = e^{-x^2}$.

- It may be possible to find an antiderivative symbolically, but it may be easier to compute a numerical approximation than to compute the antiderivative. That may be the case if the antiderivative is given as an infinite series or product, or if its evaluation requires a special function that is not available.

* Methods

- [[id:1b852925-8aef-4a47-a83f-e7c113dff368][simpsons rule]]
- [[id:b05ec0fe-9378-4e07-b1b0-590a4b64f411][trapezoidal rule]]
