;;; evm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evm.el

(autoload 'evm-find "evm" "\
Find FILE in the currently selected Emacs installation.

(fn FILE)")
(autoload 'evm-emacs "evm" "\
Return absolute path to Emacs binary.")
(autoload 'evm-emacsclient "evm" "\
Return absolute path to Emacsclient binary.")
(register-definition-prefixes "evm" '("evm-"))

;;; End of scraped data

(provide 'evm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evm-autoloads.el ends here
