:PROPERTIES:
:ID:       0965a1f9-cf81-49b1-ac01-1047eb242990
:END:
#+title: equation of a plane in 3d

The equation of a plane in 3D is a formula representing a plane. *You need a point and a direction vector orthogonal to $\vec{P_0 P}$.*

Given a vector between two points $\vec{P_0 P}$ and another vector $\vec{n}$ *(orthogonal)*, you can use the *dot product*:

$\vec{n} \bot \vec{P_0 P} \rightarrow \vec{n} \cdot \vec{P_0 P} = 0$

$\langle a,b,c \rangle \cdot \langle x - x_0, y - y_0, z - z_0 \rangle = 0$

The result of the dot product *is the equation of a plane*:

$a(x-x_0) + b(y - y_0) + c(z - z_0) = 0$

When you have 3 points, *you can use the cross product to find the orthogonal vector.*

** Parallel planes

If the planes are parallel, *they have the same normal vector.*

** Perpendicular planes

If the planes are perpendicular, *they have perpendicular normal vectors*.

** Angles of 2 planes

To find the angle of 2 planes, *find the angle of the normal vectors*, a fast way is by the cosine formula (dot product).

** Angle between a line and a plane

To find the angle between a line and a plane, use the cosine formula (dot product) for the *normal vector of the plane* and the *direction vector of the line*:

$\cos \theta = \frac{|\vec{n} \cdot \vec{v}|}{\Vert \vec{n} \Vert \cdot \Vert \vec{v} \Vert}$

The angle is the formula:

$\textrm{angle} = 90^{\circ} - \cos^{-1} (\frac{|\vec{n} \cdot \vec{v} |}{\Vert \vec{n} \Vert \cdot \Vert \vec{v} \Vert})$

** Intersection of a line into a plane

To find the intersection of a plane and a line, *plug the points of the line in the equation of the plane*. After that, solve for $t$ in the equation of that line.

** Equation for line of intersection of 2 planes

Take the *cross product of the normal vectors* of these 2 planes, $\vec{n_1} \times \vec{n_2}$. This will be your *direction vector*.

*Set $x,y$ or $z$ to 0* in the two equations of the planes, and solve the system. This will be your *point*. Use the point and the direction vector to find the [[id:5fe6e541-b930-4081-be95-22ef5386afc5][equation of line in 3D]].

** Distances
:PROPERTIES:
:ID:       c2f74506-40bd-4153-8cc2-f8b65a163985
:END:

***** Distance of a point and a plane

Use *vector projection* to project $\vec{P_1}$ onto the normal vector of the plane, the result is the following equation:

$D = \frac{|ax_1 + by_1 + cz_1 - d|}{\sqrt{a^2 + b^2 + c^2}}$

***** Distance of parallel planes

Parallel planes have the *same normal vector*:

$D = \frac{| d_1 - d_2 |}{\sqrt{a^2 + b^2 + c^2}}$

***** Distance between skew lines

Since skew lines $\vec{P_1}$ and $\vec{P_2}$ can be contained in parallel planes, find the *direction vector* $\vec{v_1}$ and $\vec{v_2}$ of both lines. *Take the cross product $\vec{v_1} \times \vec{v_2} = \vec{w}$*.

Since parallel planes have the same normal vectors $\vec{w}$, *find the equation of the planes* and take the distance using the *equation of distance of parallel planes*.

***** Distance between a point and a line

Using trigonometry relations and cross product:

$D = \frac{\Vert \vec{u} \times \vec{v} \Vert}{\Vert \vec{v} \Vert}$

$\vec{v}$ is the direction vector of the line, and $\vec{u}$ is the vector $\vec{P_0P_1}$.
