:PROPERTIES:
:ID:       aa80d962-1f13-4297-99d3-d5cd86f7de2b
:END:
#+title: encoding

Memory has the ability to *encode, store and recall* information. Memories give an organism the capability to *learn and adapt* from previous experiences as well as build relationships.

Encoding allows a perceived item of use or *interest* to be converted into a construct that can be stored within the brain and recalled later from long-term memory.

Working memory stores information for *immediate use or manipulation* which is aided through hooking onto *previously archived items* already present in the long-term memory of an individual.

* Process of encoding
:PROPERTIES:
:ID:       fad264fd-6cc6-48ba-9388-dd18ecca2258
:END:

Encoding is a biological event that begins with *perception*. All perceived and striking sensations travel to the brain's thalamus where all these sensations are combined into *one single experience*.

The [[id:26ca2c81-06c2-49a9-8067-39fd547cd1d6][*hippocampus*]] is responsible for analyzing these inputs and ultimately *deciding if they will be committed to long-term memory*. These various threads of information are stored in various parts of the brain. However, the exact way in which these pieces are identified and recalled later remains unknown.

** Molecular process
:PROPERTIES:
:ID:       796ffea2-618f-4f28-a669-f27005cd89c5
:END:

Encoding is achieved using a combination of [[id:9ac1c4c7-9cba-48de-b673-7f0e0c56d3df][chemicals and electricity]].

* Molecular perspective of encoding

The process of encoding is not yet well understood, however key advances have shed light on the nature of these mechanisms.

Encoding begins with any novel situation, as the brain will interact and draw conclusions from the results of this interaction. These learning experiences have been known to trigger a cascade of molecular events leading to the *formation of memories*.

 These changes include the modification of neural synapses, modification of proteins, creation of new synapses, activation of gene expression and new protein synthesis.

One study found that *high central nervous system levels of acetylcholine during wakefulness aided in new memory encoding*, while *low levels of acetylcholine during slow-wave sleep aided in consolidation of memories*.

* Types of encoding
:PROPERTIES:
:ID:       95df0950-83fa-4d85-a66e-39f27d24335c
:END:

There are many types of mental encoding that are used, such as visual, elaborative, organizational, acoustic, and semantic.

** Visual encoding
:PROPERTIES:
:ID:       a7ce4e23-10ce-428d-a10b-8d84ac39dae9
:END:

Visual encoding is the process of *converting images and visual sensory information* to memory stored in the brain.

*This means that people can convert the new information that they stored into mental pictures.*

Visual sensory information is temporarily stored within our *iconic memory and working memory* before being encoded into permanent long-term storage.

The [[id:0aca85c5-b824-4046-b0a8-cedd1d69cb79][amygdala]] is another complex structure that has an important role in visual encoding. It accepts visual input in addition to input, from other systems, and *encodes the positive or negative values* of conditioned stimuli.

** Elaborative encoding
:PROPERTIES:
:ID:       6f7098f7-ed60-43d9-9219-ca9f0e49baba
:END:

Elaborative encoding is the process of actively *relating new information to knowledge that is already in memory*.

Memories are a *combination of old and new information*, so the nature of any particular memory depends as much on the old information already in our memories as it does on the new information coming in through our senses.

** Semantic encoding
:PROPERTIES:
:ID:       89834a24-e3bb-41cf-878a-11d5015ec8fe
:END:

Semantic encoding is the processing and encoding of sensory input that has *particular meaning or can be applied to a context*.

Words studied in semantic or deep encoding conditions are *better recalled* as compared to both easy and hard groupings of nonsemantic or shallow encoding conditions with response time being the deciding variable.

* Methods to better encoding
:PROPERTIES:
:ID:       b47ecf91-b7df-4fa9-a60c-327673d9455f
:END:

** Visual images
:PROPERTIES:
:ID:       0414fed8-854c-4adc-8904-094d9eb9c64f
:END:

A method used to enhance encoding is to *associate the information with images*. Some articles suggest that visual images can improve encoding significantly.

** Chunking
:PROPERTIES:
:ID:       78be4ab8-a472-401e-862e-747bf5f81094
:END:

Chunking is a method used to *improve [[id:6ac3436e-4f40-4460-aca0-d9bb8e659ecd][Short term memory]]* by organizing informations into *small groups*. By organizing objects into meaningful sections, these sections are then remembered as a unit rather than separate objects.

As larger sections are analyzed and connections are made, information is weaved into meaningful associations and *combined into fewer, but larger and more significant pieces of information*. 

One of the most common forms of chunking seen on a daily basis is that of phone numbers.

** State Dependent Learning
:PROPERTIES:
:ID:       4053a01d-3113-4507-8170-e5c4e2586978
:END:

For optimal encoding, connections are not only formed between the items themselves and past experiences, but also *between the internal state or mood of the encoder and the situation they are in*.

Although the external environment is important at the time of encoding in creating multiple pathways for retrieval, other studies have shown that *simply creating the same internal state that was present at the time of encoding* is sufficient to serve as a retrieval cue.

Therefore, *being in the same mindset as in at the time of encoding* will help with recalling in the same way that being in the same situation helps recall.

** Generation Effect
:PROPERTIES:
:ID:       d8cbca36-1771-4830-9a34-97aef7123fe0
:END:

The generation effect implies that learning is enhanced when individuals *generate information or items themselves rather than reading the content*.

According to the lexical activation hypothesis, the participant must search his or her semantic memory during the process of generation. The search activates semantic features in memory that are related to the target item.

** Retrieval Practice
:PROPERTIES:
:ID:       ca7feef2-57fe-4cc2-ad2c-bec667b546e8
:END:

Studies have shown that an effective tool to increase encoding during the process of learning is to *create and take practice tests*, as it actively involves *creating and recreating the material* that one is intending to learn and increases one’s exposure to it.

Thus, creating practice tests allows the individual to *process the information at a deeper level* than simply reading over the material again or using a pre-made test.
